[metadata]
name = networking-srv6
summary = SRv6 ML2 type driver for OpenStack Neutron
description-file = README.rst
license = Apache-2
author = costa99
home-page = https://github.com/costa99/networking-srv6
classifiers =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 3

[files]
packages =
    networking_srv6

[entry_points]
neutron.ml2.type_drivers =
    srv6 = networking_srv6.plugins.ml2.drivers.srv6.type_srv6:SRv6TypeDriver
neutron.db.alembic_migrations =
    networking-srv6 = networking_srv6.db.migration:alembic_migrations
